version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Refers to your custom Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" # Puerto por defecto de PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos
volumes:
  postgres_data:
 