name: Node build project
run-name: Build nodejs project
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted]
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: |
          cd clientManager
          npm install
      - name: Compile
        run: |
          cd clientManager
          npm run build