name: Node Lint
run-name: Lint Node.js App

on: [push]

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: |
          cd calculadora
          npm install

      - name: Lint
        run: |
          cd calculadora
          npm run lint
